server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/espra_backend
    password: 123faizanmemon
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  algorithm:
    key: SuperSecureSecretKey
  issuer: eCommerce
  expiryInSeconds: 604800
